name: Test
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org

      - name: Restore yarn cache if available
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run TypeScript type checker
        run: |
          yarn ts:check
        env:
          CI: true

      - name: Run formatting check
        run: |
          yarn format:check
        env:
          CI: true

      - name: Run linting check
        run: |
          yarn lint
        env:
          CI: true

      - name: Run tests
        run: |
          yarn test:ci
        env:
          CI: true

      - name: Upload coverage
        uses: codecov/codecov-action@v3
